GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root';
CREATE DATABASE IF NOT EXISTS dev;
USE dev;
CREATE TABLE IF NOT EXISTS employee
 (
    ID INT(10) NOT NULL, 
    NAME VARCHAR(255), 
    DEPT VARCHAR(255), 
    AGE INT(10), 
    PRIMARY KEY(ID)
 );